#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc rule -a firefox desktop=^2
bspc rule -a discord desktop=^3
bspc rule -a steam desktop=^4
bspc rule -a code desktop=^1

bspc monitor -d ">_" WWW "[=]" "{..}" "~/" "e^πi"  "⊙)" "@$" "\\/" "-_-"

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
