#!/bin/bash

# Function to source files if they exist
function zsh_add_file() {
    [ -f "$HOME/.local/share/zsh/$1" ] && source "$HOME/.local/share/zsh/$1"
}

function zsh_add_plugin() {
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$HOME/.local/share/zsh/plugins/$PLUGIN_NAME" ]; then
        # For plugins
        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.zsh"
    else
        git clone "https://github.com/$1.git" "$HOME/.local/share/zsh/plugins/$PLUGIN_NAME"
    fi
}

function zsh_add_completion() {
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$HOME/.local/share/zsh/plugins/$PLUGIN_NAME" ]; then
        # For completions
		completion_file_path=$(ls $HOME/.local/share/zsh/plugins/$PLUGIN_NAME/src)
		fpath+="$(dirname "${completion_file_path}")"
        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh"
    else
        git clone "https://github.com/$1.git" "$HOME/.local/share/zsh/plugins/$PLUGIN_NAME"
		fpath+=$(ls $HOME/.local/share/zsh/plugins/$PLUGIN_NAME/src)
		rm $HOME/.local/share/zsh/.zccompdump
    fi
	if [ "$2" = true ] && compinit
}

function gitbatdiff() {
	    git diff --name-only --relative --diff-filter=d | xargs bat --diff
}

function gitbatshow() {
	git show "$1" | bat -l rs
}

function tailbat() {
	tail -f "$1" | bat --paging=never -l log
}


function xclipbat() {
	bat "$1" | xclip
}
