#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefoxdeveloperedition desktop='^2' focus=on
bspc rule -a vscodium desktop='^3' focus=on
bspc rule -a discord desktop='^4' focus=on
