#!/usr/bin/env bash

COMMIT_MSG_FILE=$1

# Check errors duplicated signatures
test "" = "$(grep '^Signed-off-by: ' "$COMMIT_MSG_FILE" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 Duplicate Signed-off-by lines.
	exit 1
}

exit 0 
